/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DrinkDetail: typeof import('./components/DrinkDetail.vue')['default']
    DrinksMenu: typeof import('./components/DrinksMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VAlerts: typeof import('./components/controls/VAlerts.vue')['default']
  }
}
